name: salsa_challenge
description: "Desafio Técnico Flutter Salsa Technology - Paulo Gabriel Andrade de Souza"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8

  mobx: ^2.3.0
  flutter_mobx: ^2.2.1

  get_it: ^7.6.7

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  go_router: ^14.2.7

  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

  build_runner: ^2.4.8
  mobx_codegen: ^2.3.0

  mocktail: ^1.0.3
  hive_test: ^1.0.1

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/html/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/favicon.png"